templates changes and fixes
KacperSiak/Pralnia-projekt pull request #17
Opened 2024-06-04 18:46 UTC by KacperSiak

2024-06-04 19:06 UTC, ms1707 commented on stock/templates/stock/stock_list.html
> +{% block title %}TLista asortymnetu{% endblock title %}
Literówka TLista

2024-06-04 19:06 UTC, ms1707 commented on stock/templates/stock/stock_create.html
> +{% block title %}TNowy asortyment{% endblock title %}
Literówka TNowy

2024-06-04 19:07 UTC, ms1707 requested changes
Dwie literówki w tytułach bloków

2024-06-04 19:31 UTC, ms1707 approved these changes

2024-06-05 11:22 UTC, Bala22100 approved these changes

2024-06-05 13:58 UTC, merged